### ISSUE TITLE
Issue in Modal 

### ISSUE THREAD

**Issue by pratikkabade** [pratikkabade/cryptoSpy#1]
![image](https://user-images.githubusercontent.com/76637730/179253143-e15066fe-f74e-437e-bfd0-b335acae1cba.png)

Every card opens first modal instead of respective modal

Reference to the code
https://github.com/pratikkabade/cryptoSpy/blob/9b597be853b9cfcfba1e42d2785afb0438dccdc0/src/pages/Coin.js#L6

**Comment by vidhanshu** [comment]
please assign this issue to me

**Comment by pratikkabade** [comment]
fixed
