### ISSUE TITLE
To make an individual page of Crypto like of Modal

### ISSUE THREAD

**Issue by pratikkabade** [pratikkabade/cryptoSpy#4]
To add new page such that it will show entire crypto details on new page

![image](https://user-images.githubusercontent.com/76637730/181005778-9c0a8842-383e-4493-b1ff-f6608f8f4690.png)

like this but in a new page

**Comment by pratikkabade** [comment]
@vidhanshu could you do this as well?

**Comment by vidhanshu** [comment]
sure

**Comment by pratikkabade** [comment]
👍🤝

**Comment by vidhanshu** [comment]
will you design that page after implementing it by me?

**Comment by vidhanshu** [comment]
will you design that page after implementing it by me?

**Comment by pratikkabade** [comment]
Yeah. Designing isn't it big work.
It's connecting those two individual pages which is taking long for me
So I'll design after you implement it.

**Comment by vidhanshu** [comment]
Actually, i have created the pr, But i changed the home page route so if you merge it will say **no route exists** `/cryptoSpy` 
home page route `/`
coin details route `/coin-details/id`
